### ISSUE TITLE
Input examples for ARclassify.py and GREATstyle_...py

### ISSUE THREAD

**Issue by madzafv** [jacahill/AR_Tools#1]
Hello James, I'm trying to use your scripts to analyze some of my Bengalese finch data, but I can't quite follow the code having the canonical gff annotation format in mind. Would you mind providing some pieces of input files?
Thank you!

**Comment by jacahill** [comment]
Hi,

The input is UCSC's .bed format (https://genome.ucsc.edu/FAQ/FAQformat.html#format1) and formats derivative of .bed. I'll get a sample up asap but briefly any tab delimited files with the first three columns being:
chromosome    regionStart    regionEnd

This includes the standard output of phyloP which is the standard use case for this data.

Best,
James

**Comment by madzafv** [comment]
Got it! Thnak you
